[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
optimizer = true
optimizer_runs = 1000000
via_ir = true
evm_version = "cancun"

[profile.production]
optimizer_runs = 10000000
via_ir = true

[fuzz]
runs = 256

[rpc_endpoints]
polygon = "${POLYGON_RPC_URL}"
mumbai = "${MUMBAI_RPC_URL}"
